name: Delete merged branch on PR close

on:
  pull_request:
    types:
      - closed

jobs:
  delete-merged-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          REPO=${{ github.repository }}
          echo "Deleting branch $BRANCH_NAME from $REPO"

          curl -s -X DELETE \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/git/refs/heads/$BRANCH_NAME"
